language: bash

# Doc
# - Travis Job Lifecycle : https://docs.travis-ci.com/user/job-lifecycle/

matrix:
  include:
    - name: "Linux Debug"
      os: linux
      dist: xenial
      env:
        - MODE=Debug
    - name: "Linux Release"
      os: linux
      dist: xenial
      env:
        - MODE=Release
    - name: "MacOS Debug"
      os: osx
      osx_image: xcode9.4
      env:
        - MODE=Debug
    - name: "Windows Debug"
      os: windows
      # Help : https://travis-ci.community/c/environments/windows
      # Pre-installed packages: https://docs.travis-ci.com/user/reference/windows/
      # use `choco` command
      env:
        - MODE=Debug
    - name: "Linux Coverage"
      os: linux
      dist: xenial
      compiler: clang
      env:
        - MODE=Coverage
      addons:
        apt:
          update: true
          packages:
            - lcov
#    # Disabled because too long
#    - name: "MacOS Coverage"
#      os: osx
#      osx_image: xcode9.4
#      env:
#        - MODE=Coverage
#      addons:
#        homebrew:
#          update: true
#          packages:
#            - lcov

install:
  - >
    if [[ "$MODE" == "Coverage" ]]; then
      if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "osx" ]]; then
        gem install coveralls-lcov
      fi
      if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      echo "Coverage not supported for Windows"
      travis_terminate 1
      fi
    fi

before_script:
  - > # to debug environment use 'true'
    if ( false ); then
      echo $PATH
      if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "osx" ]]; then
        c++ --version
      fi
      cmake --version
    fi
  - >

script:
  # - set -eo pipefail
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake .. -DCMAKE_BUILD_TYPE=${MODE}
      cmake --build .
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cmake ..
      cmake --build . --target ALL_BUILD --config ${MODE}
    fi
  - >
    if [[ "$MODE" == "Coverage" ]]; then
      # Windows os has been filtered out in install step
      make coverage
    else
      ctest -C ${MODE} # --verbose
    fi

#addons:
#  artifacts:
#    debug: false
#    paths:
#      - ${HOME}/build

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - >
    if [[ "$MODE" == "Coverage" ]]; then
      lcov --list coverage.info
      coveralls-lcov coverage.info
    fi
