language: bash

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - MODE=Debug
    - os: linux
      dist: xenial
      env:
        - MODE=Release
    - os: osx
      osx_image: xcode9.4
      env:
        - MODE=Debug
    - os: windows
      # https://travis-ci.community/c/environments/windows
      env:
        - MODE=Debug

before_install:
  - echo $PATH
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      # apt-get --help
      g++ --version
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # brew --help
      clang++ --version
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      # Pre-installed packages: https://docs.travis-ci.com/user/reference/windows/
      # choco --help
      clang++ --version
    fi
  - cmake --version

# Build steps
script:
  # - set -eo pipefail
  - cd ${TRAVIS_BUILD_DIR}
  - echo ${PWD}
  - mkdir build && cd build
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake .. -DCMAKE_BUILD_TYPE=${MODE}
      cmake --build .
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cmake ..
      ls -l
      cmake --build . --target ALL_BUILD --config ${MODE}
    fi
  - ctest -C ${MODE}

#addons:
#  artifacts:
#    debug: false
#    paths:
#      - ${HOME}/build

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - echo "Success"