language: bash

env:
  - MODE=Debug

#os:
#  - linux
#  - osx
#  - windows

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode9.4
    - os: windows
      # https://travis-ci.community/c/environments/windows

before_install:
  - echo $PATH
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      # apt-get --help
      g++ --version
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # brew --help
      clang++ --version
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      # Pre-installed packages: https://docs.travis-ci.com/user/reference/windows/
      # choco --help
      clang++ --version
      choco install make
    fi
  - cmake --version

# Build steps
script:
  # - set -eo pipefail
  - cd ${TRAVIS_BUILD_DIR}
  - echo ${PWD}
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${MODE} || cat CMakeFiles/CMakeOutput.log
  - ls -l
  - make
  - ctest -C ${MODE}

#addons:
#  artifacts:
#    debug: false
#    paths:
#      - ${HOME}/build

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - echo "Success"