language: bash

# Doc
# - Travis Job Lifecycle : https://docs.travis-ci.com/user/job-lifecycle/

matrix:
  include:
    - name: "Linux Debug"
      os: linux
      dist: xenial
      env:
        - BUILD_NAME="linux-macos"
        - MODE=Debug
      addons:
        apt:
          packages:
            - liblapack-dev

    - name: "Linux Release"
      os: linux
      dist: xenial
      env:
        - BUILD_NAME="linux-macos"
        - MODE=Release
      addons:
        apt:
          packages:
            - liblapack-dev

    - name: "MacOS Debug"
      os: osx
      osx_image: xcode9.4
      env:
        - BUILD_NAME="linux-macos"
        - MODE=Debug

    # Help : https://travis-ci.community/c/environments/windows
    # Pre-installed packages: https://docs.travis-ci.com/user/reference/windows/
    # use `choco` command as package command
    - name: "Windows Debug"
      os: windows
      env:
        - BUILD_NAME="windows"
        - MODE=Debug

#    - name: "Windows Release"
#      os: windows
#      env:
#        - BUILD_NAME="windows"
#        - MODE=Release

    - name: "Linux Coverage"
      os: linux
      dist: xenial
      compiler: clang
      env:
        - BUILD_NAME="linux-macos"
        - MODE=Coverage
      addons:
        apt:
          update: true
          packages:
            - liblapack-dev
            - lcov

#    # Disabled because too long
#    - name: "MacOS Coverage"
#      os: osx
#      osx_image: xcode9.4
#      env:
#        - BUILD_NAME="linux-macos-coverage"
#        - MODE=Coverage
#      addons:
#        homebrew:
#          update: true
#          packages:
#            - lcov

    - name: "R Linux"
      os: linux
      dist: xenial
      env:
        - DEBUG_CI=true
        - BUILD_NAME="r-linux-macos"
      addons:
        apt:
          packages:
            - liblapack-dev
            - r-base
            - r-base-core
            - r-base-dev

    - name: "R MacOS"
      os: osx
      osx_image: xcode9.4
      env:
        - DEBUG_CI=true
        - BUILD_NAME="r-linux-macos"
      addons:
        homebrew:
          update: true
          packages:
            - r

install:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/install.sh

before_script:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/before_script.sh

script:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/script.sh

#addons:
#  artifacts:
#    debug: false
#    paths:
#      - ${HOME}/build

after_success:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/after_success.sh
