language: bash

env:
  - MODE=Debug

#os:
#  - linux
#  - osx
#  - windows

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode9.4
    - os: windows
      # https://travis-ci.community/c/environments/windows

before_install:
  - echo $PATH
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      apt-get --help ; g++ --version
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew --help ; clang++ --version
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco --help
      # Pre-installed packages: https://docs.travis-ci.com/user/reference/windows/
      clang++ --version
      # msvc /help # not found in PATH
    fi

# Build steps
script:
  - cd ${TRAVIS_BUILD_DIR}
  - echo ${PWD}
  - ls -l

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - echo "Success"